# Geomtery Analysis Project

In [1]:
import os
import numpy

In [2]:
pwd

'C:\\Users\\train721\\Desktop\\data'

In [17]:
file_location = os.path.join('water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2, dtype='unicode')
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
print(symbols)
coordinates = coordinates.astype(numpy.float)
print(coordinates)
num_atoms = len(symbols)
print(num_atoms)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
3


In [19]:
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        distance_12 = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
        print(F'{symbols[num1]} to {symbols[num2]} : {distance_12}')                                              

O to O : 0.0
O to H1 : 0.9690005374652793
O to H2 : 0.9690003348647513
H1 to O : 0.9690005374652793
H1 to H1 : 0.0
H1 to H2 : 1.52693633514957
H2 to O : 0.9690003348647513
H2 to H1 : 1.52693633514957
H2 to H2 : 0.0


In [33]:
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
        if num1>num2:
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            distance_12 = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
            print(F'{symbols[num1]} to {symbols[num2]} : {distance_12}')                                              

H1 to O : 0.9690005374652793
H2 to O : 0.9690003348647513
H2 to H1 : 1.52693633514957


In [46]:
#def function_name(parameters):
#    *****code goes******
#    return value_to_return

In [70]:
def calculate_distance(coords1, coords2):
    """
    
    This function is something because you didn't make it in time.
    This function has two arguments, the coordinates of two atoms. 
    It returns the distance between the atoms.
    
    """
    x_distance = coordinates[0] - coordinates2[0]
    y_distance = coordinates[1] - coordinates2[1]
    z_distance = coordinates[2] - coordinates2[2]
    distance_12 = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
    return distance_12

In [77]:
def bond_check(distance,minimum=0,maximum=1.5):
    """
    
    Checks a distance to see if it's a bond. User specifies minimum and maximum values. 
    
    """
    if distance>minimum and distance_12<maximum:
        return True
    else:
        return False

In [78]:
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
        if num1>num2:
            distance_12 = calculate_distance(coordinates[num1], coordinates[num2])
            #x_distance = coordinates[num1,0] - coordinates[num2,0]
            #y_distance = coordinates[num1,1] - coordinates[num2,1]
            #z_distance = coordinates[num1,2] - coordinates[num2,2]
            #distance_12 = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
            if bond_check(distance_12,0,1.5) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance_12:.3f}')  

NameError: name 'coordinates2' is not defined

In [75]:
help(calculate_distance)                                       

Help on function calculate_distance in module __main__:

calculate_distance(coords1, coords2)
    This function is something because you didn't make it in time.
    This function has two arguments, the coordinates of two atoms. 
    It returns the distance between the atoms.

